### ISSUE TITLE
Code not compiling when in a .net core Standard Library

### ISSUE THREAD

**Issue by MartinSher** [joelmartinez/dotnet-core-roslyn-sample#1]
Hi

Using the sample code, using VS2017 .net core 1.4 I can get the line of code

MetadataReference.CreateFromFile(typeof(object).GetTypeInfo().Assembly.Location)

to compile if it is in my application project using the Microsoft.NetCore.App SDK. However, it does not compile when in the Standard class project using the NETStandard.Library SDK.

Similar issues with referencing the System.Runtime.Loader assembly.

Any ideas to to how to overcome this so that I can compile code from within a standard class library which is common to various application projects?

Thanks Martin

**Comment by joelmartinez** [comment]
Thanks for reporting this @MartinSher !
